version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Delay
          command: sleep 10m
      - run:
          name: Print the Current Time
          command: date
      
